### ISSUE TITLE
Ability to select backend

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#101]
It seems that depending on the settings in my Nvida Conrol Panel (whether I select Integrated Graphics or the NVidea GPU), wgpu will use either the Vulkan or DX12 backend. With the DX12 backend I run into crashes for some code, which I should probably look into at some point, but it would be nice to just force the use of the Vulkan backend for now. Also because (in my understanding) the Vulkan backend is more mature.

Is this something that could be added to wgpu-native, e.g. in the form of an additional function `wgpuInstanceRequestAdapterSelectBackend` that has an extra argument for the backend bits? This would make the API deviate from webgpu, but its something that might be worthy for desktop use (similar to e.g. the tracing functionality). I'd be happy to prepare a PR for this.

**Comment by DevOrc** [comment]
We could probably add a custom struct that can be chained into the `InstanceDescriptor` like DeviceExtras

https://github.com/gfx-rs/wgpu-native/blob/7643e9ff7f25e0059f5fb5b62923b5b483551418/ffi/wgpu.h#L13-L18

Something along the lines of 

```c
typedef struct WGPUInstanceExtras {
    WGPUChainedStruct chain;
    WGPUBackendBit backend;
} WGPUInstanceExtras ;
```

**Comment by almarklein** [comment]
Out of curiosity, why is DX12 chosen over Vulkan ?

**Comment by cwfitzgerald** [comment]
DX12 will only be chosen over vulkan if no vulkan adapter exists. We always choose in the order `Vulkan > Metal > DX12 > DX11 > GL`

**Comment by almarklein** [comment]
> DX12 will only be chosen over vulkan if no vulkan adapter exists.

Then I suspect something might be wrong in this selection process. If I select "NVidea GPU" in my control panel, wgpu will use the DX12 backend (as I described in the top post). But when I set the backendbit to exclude DX (in #102), it runs just fine.

**Comment by almarklein** [comment]
Referencing https://github.com/gfx-rs/wgpu/issues/1416 where we seem to have found the cause of DX12 being selected over Vulkan. In short: DX12 seems to ignore the control panel settings, and can select integrated or discrete even if the other is selected, and therefore the DX12 backend can match the requested power_preference better, causing it to be selected over Vulkan.
