### ISSUE TITLE
Naga error messages not as useful as they could be

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#104]
When the provided WGSL shader code is invalid, the error messages are usually less useful than if I run Naga directly on that shader code.

Example:
```wgsl
...
return vec4<f32>(value, value, value, 1);
```

wgpu-native:
```
Vector component[3] type Scalar { kind: Sint, width: 4 }
thread '<unnamed>' panicked at 'Validation(EntryPoint { stage: Fragment, name: "fs_main", error: Function(Expression { handle: [9], error: Compose(ComponentType { index: 3 }) }) })', src\device.rs:87:5
```

Naga:
```
Entry point fs_main at Fragment is invalid:
        Expression [9] is invalid
        Composing 3's component type is not expected
error: process didn't exit successfully: `target\debug\naga.exe c:/dev/py/tmp.wgsl` (exit code: 0xffffffff)
```

With naga it will sometimes also indicate where in the code the error occurs.

Is this something that can be improved somehow?

**Comment by kvark** [comment]
Absolutely! The error function needs to walk the chain of errors, not just debug print it (`{:?}`). See https://github.com/gfx-rs/naga/blob/72fca17dbc56a33acdf53ab6eab113386a774731/bin/naga.rs#L26

**Comment by almarklein** [comment]
Is that link where a change would be needed to fix this, or is this the function that should be called instead in wgpu-core?

**Comment by kvark** [comment]
This is an example of properly printing out the error chain. wgpu-native need similar logic in order to spew out readable messages.

**Comment by almarklein** [comment]
I think this is where a change would be needed:

https://github.com/gfx-rs/wgpu/blob/eadaa1b7d8f585761e28445904fe619b180aca0d/wgpu-core/src/device/mod.rs#L1041-L1052

I had a quick try inserting the referenced lines there, but get:
```
let mut e = err.source();
                ^^^^^^ method not found in `naga::front::wgsl::ParseError
```

**Comment by kvark** [comment]
Do you have `std::error::Error` in scope? Try adding `use std::error::Error`.

**Comment by almarklein** [comment]
Ah, that helps getting the code to compile. But the error reporting is not getting better. I just saw [this maybe related comment](https://github.com/gfx-rs/naga/pull/934#discussion_r644096246), looks like someone else is trying to achieve something similar for glsl.

**Comment by kvark** [comment]
Hmm. Error reporting is already there for WGSL though, and this is what you are testing.
What does it look like currently with these changes?

**Comment by almarklein** [comment]
Here's what I got so far: https://github.com/gfx-rs/wgpu/pull/1424

**Comment by almarklein** [comment]
This has been fixed upstream.
