### ISSUE TITLE
wgpuQueueWriteTexture panic on MacOS

### ISSUE THREAD

**Issue by ryhor-spivak** [gfx-rs/wgpu-native#105]
I'm running into rust panics on wgpuQueueWriteTexture on MacOS

thread '<unnamed>' panicked at 'index out of bounds: the len is 1 but the index is 3875379856', /Users/qwerty/.cargo/git/checkouts/wgpu-53e70f8674b08dd4/7ce535c/wgpu-core/src/hub.rs:125:45

Here is a modified examples/triangle/main.c which reproduce this issue:

https://gist.github.com/ryhor-spivak/a119e6caaa15bd69eb91f9bdb1b844e9

I suspect there is a difference in some structure layout between C and Rust code as adding stack variables around WGPUTextureDescriptor / WGPUImageCopyTexture / WGPUTextureDataLayout / WGPUExtent3D changes index value in panic message.

Same code works fine on Windows with Vulkan backend.

**Comment by DevOrc** [comment]
This looks like a bug in #95 

https://github.com/gfx-rs/wgpu-native/blob/7643e9ff7f25e0059f5fb5b62923b5b483551418/src/device.rs#L341-L349

The `destination` ,`data_layout` and `write_size`, should be passed by references.
