### ISSUE TITLE
Symbols missing in v0.8.0.2 - wgpu-windows-64-release.zip

### ISSUE THREAD

**Issue by Tezza48** [gfx-rs/wgpu-native#116]
Windows 10
Visual Studio 2019
Release: https://github.com/gfx-rs/wgpu-native/releases/tag/v0.8.0.2

Many symbols are missing from the libs in `wgpu-windows-64-release.zip` this includes all `wgpuCreate*` functions.

This is leading to the following Linker error `error LNK2001: unresolved external symbol __imp_wgpuCreateInstance`.

Here is the dumpbin output for the exported symbols in wgpu_native.dll https://gist.github.com/Tezza48/00aa309c1156955cf4c8ef27e347a495

**Comment by Tezza48** [comment]
I've now installed the dependencies to build from source and the issue is present in the build artefacts.

**Comment by DevOrc** [comment]
Currently wgpu-native does not use instances. For now, the examples just pass NULL for the instance. 

https://github.com/gfx-rs/wgpu-native/blob/6dddc5567566aebc52d18bdcbc985554f5b840ae/examples/triangle/main.c#L112-L119

**Comment by Tezza48** [comment]
Thanks.
