### ISSUE TITLE
CD is broken because 'libclang function not loaded'

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#118]
This [commit](https://github.com/gfx-rs/wgpu-native/pull/114/commits/f01a13cd9e80ed0c5d11270390d7e855512c3541) bumps the version of the `bindgen` dependency, solving an issue for MacOS on M1 chips. However, it also breaks the CD build with the manylinux Docker containers, see [this CD run](https://github.com/gfx-rs/wgpu-native/runs/2977262123?check_suite_focus=true).

Also see [my (yet unseccesful) attempt to fix this](https://github.com/almarklein/wgpu-native/pull/3).

**Comment by almarklein** [comment]
The error in more detail:
```
 thread 'main' panicked at '`libclang` function not loaded: `clang_Cursor_isMacroFunctionLike`. This crate requires that `libclang` 3.9 or later be installed on your system.
```

It loos like the version of libclang is insufficient:
```
Installed:
  clang.x86_64 0:3.4.2-4.el6             zip.x86_64 0:3.0-1.el6_7.1            

Dependency Installed:
  llvm.x86_64 0:3.4.2-4.el6            llvm-libs.x86_64 0:3.4.2-4.el6   
```

**Comment by kvark** [comment]
So bindgen dragged in newer clang, and it's hard to update it on some of the Linux images? That's quite unfortunate :(

**Comment by almarklein** [comment]
Yes, that looks like a good summary.
