### ISSUE TITLE
Missing object destroy functions

### ISSUE THREAD

**Issue by helikopterodaktyl** [gfx-rs/wgpu-native#119]
The current interface only has functions for destroying Buffers, Textures and Query Sets. It doesn't have functions for destroying other GPU objects such as Samplers, Render/Compute Pipelines, Bind Groups, ShaderModules and possibly others.

**Comment by ryhor-spivak** [comment]
Now there are *Drop methods in wgpu.h. What is relationship between those and existing wgpuBufferDestroy, wgpuTextureDestroy, wgpuQuerySetDestroy?

**Comment by cwfitzgerald** [comment]
Destroy is immediate destruction of the resource -- any future uses, including those in already existing BindGroups -- is invalid and will throw an error.

Drop says that the user is done with their handle to the object, but already existing BindGroups etc can keep the object alive.

**Comment by cwfitzgerald** [comment]
Closing this as wgpu-native now has the required functions. webgpu-native can bikeshed in it's own time.

**Comment by kvark** [comment]
If you know you may still have resources referencing this, like stale bind groups, or views, but you want to force the destruction anyway.
