### ISSUE TITLE
How would I use wgpuBufferMapAsync without wgpuDevicePoll?

### ISSUE THREAD

**Issue by athas** [gfx-rs/wgpu-native#121]
[The compute example uses wgpuDevicePoll](https://github.com/gfx-rs/wgpu-native/blob/master/examples/compute/main.c#L126) to block until the memory is mapped.  This works, but `wgpuDevicePoll` is wgpu-specific and in particular does not work with Emscripten.  The JS API returns a promise that can be used for blocking here, but how would I do it with wgpu-native?  I understand that the webgpu.h header is WIP, so is this just a problem that hasn't been addressed yet?

**Comment by athas** [comment]
Also, apologies if this is not the right place to ask.  I couldn't find any chat room or similar.

**Comment by kvark** [comment]
We'll need something like "poll" in https://github.com/webgpu-native/webgpu-headers . Care to file an issue there? Thank you!

**Comment by athas** [comment]
I have done so: https://github.com/webgpu-native/webgpu-headers/issues/91
