### ISSUE TITLE
Cannot select off board GPU when integrated GPU is present

### ISSUE THREAD

**Issue by EnzoAlbornoz** [gfx-rs/wgpu-native#122]
I was trying to use my laptop NVidia GPU with WebGPU when I noticed that is no "power_preference" option. Then I looked inside device.rs and verified that PowerPreference is always set as LowPower.

https://github.com/gfx-rs/wgpu-native/blob/c85b882208c64d656d68f36c3b0f710139ab9b44/src/device.rs#L32-L40

Is this intentional? I need to use the "high-performance" mode to compute expensive matrix multiplications.

**Comment by kvark** [comment]
We need to expose the power preference in https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.h

**Comment by radgeRayden** [comment]
This is kind of important in certain contexts because eg. intel drivers aren't always the best for vulkan. Can one just send a pull request for that or is it more closed to external contribution?

**Comment by kvark** [comment]
It's a community project, we are more than happy to accept contributions!

**Comment by radgeRayden** [comment]
Is anything blocking an update of the header submodule? I noticed it's a few commits behind.

**Comment by radgeRayden** [comment]
Now I'd like to make a PR to pull this change into wgpu-native proper, do I also update webgpu-headers or is that a separate PR?

**Comment by kvark** [comment]
@radgeRayden webgpu-headers is a submodule here. You'd update the submodule, and then try to build, I guess?

**Comment by radgeRayden** [comment]
Sorry you probably replied to the old version of the comment! My intention was poorly worded so I rephrased.

**Comment by kvark** [comment]
No, I think I replied to the new version?
`webgpu-headers` is a git submodule, which needs to be updated here, in the same PR that would do necessary the Rust changes. We build the Rust wrapper with `bindgen`.
