### ISSUE TITLE
Errors in shader code show complete source code instead of nice Naga errors

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#127]
Originally reported in https://github.com/gfx-rs/wgpu/pull/1760#issuecomment-904644388

The problem:
``` 
λ python examples\geometry_cube.py
Failed to parse WGSL code for Some(""): no definition in scope for identifier: 'atomicExchange'
thread '<unnamed>' panicked at 'Parsing(NagaParseError { shader_source: "\n        [[block]]\n        struct Struct_u_stdinfo {\n            cam_transform: mat4x4<f32>;\n            cam_transform_inv: mat4x4<f32>;\n            projection_transform: mat4x4<f32>;\n            projection_transform_inv: mat4x4<f32>;\n            physical_size: vec2<f32>;\n            logical_size: vec2<f32>;\n        };\n\n        [[group(0), binding(0)]]\n        var u_stdinfo: Struct_u_stdinfo;\n        \n\n        [[block]]\n        struct Struct_u_wobject {\n            world_transform: mat4x4<f32>;\n            id: i32;\n        };\n\n        [[group(0), binding(1)]]\n        var u_wobject: Struct_u_wobject;\n        \n\n        [[block]]\n        struct [... etc.]
```

In @kvark's words: In wgpu-rs, between the wgpu-core call and the user error report, there is also this piece happening [...] that's not a part of wgpu-native atm. 

https://github.com/gfx-rs/wgpu/blob/0e65b9323a2e872367dace0685a7b3278d7a9678/wgpu/src/backend/direct.rs#L146-L169

**Comment by kvark** [comment]
Would you have a test case?

**Comment by almarklein** [comment]
Have still not been able to get the examples working on Windows, but had some more luck on a Linux VM, so I can at least run the compute example :)

So, here I deliberately break the shader. Naga produces a nice error, but because newlines are escaped its barely readable:

![image](https://user-images.githubusercontent.com/3015475/134769257-274af298-990e-46f3-bf29-d8f2e4aae06e.png)

**Comment by almarklein** [comment]
Actually, the problem is not the fact the newlines are esacped, the problem is that a raw error object is printed that contains the error message and the complete shader source. The nice Naga-error is not here. I was put on the wrong track because of the formatting. Changing the title accordingly.
