### ISSUE TITLE
Q: Required lifetime of memory for `wgpuQueueWriteBuffer` and `wgpuQueueWriteTexture`?

### ISSUE THREAD

**Issue by lancelet** [gfx-rs/wgpu-native#129]
I'm working on some [Haskell bindings](https://github.com/lancelet/wgpu-hs) for wgpu-native. I'm currently trying to figure out how long the memory behind the pointers passed to `wgpuQueueWriteBuffer` and `wgpuQueueWriteTexture` must exist.

Reading the [Rust wgpu docs](https://docs.rs/wgpu/0.10.1/wgpu/struct.Queue.html#method.write_buffer), I was under the impression that the underlying memory must live until the next `wgpuQueueSubmit` call had finished:

> This method is intended to have low performance costs. As such, the write is not immediately submitted, and instead enqueued internally to happen at the start of the next submit() call.

To try to confirm this, I attempted to break my use of  `wgpuQueueWriteBuffer` by zeroing out the memory between the call to `wgpuQueueWriteBuffer` and the next call to `wgpuQueueSubmit`. To my surprise, the buffer still seemed to be copied correctly!

What is the intended usage here? Can I assume that the memory can be freed as soon as `wgpuQueueWriteBuffer` and `wgpuQueueWriteTexture` have returned? (Also: is there documentation on this already that I missed? Can I help add this to any documentation?)

**Comment by kvark** [comment]
Memory doesn't have to live any longer. You can free it right after the call.

**Comment by lancelet** [comment]
Thanks!
