### ISSUE TITLE
Replace bool with WGPUBool typedef

### ISSUE THREAD

**Issue by ghost** [gfx-rs/wgpu-native#140]
That <stdbool.h> `bool` shit will bite you in the ass real good at some point in future, consider Vulkan-like `VkBool32` typedef.

**Comment by procedural** [comment]
https://github.com/webgpu-native/webgpu-headers/issues/84

**Comment by rajveermalviya** [comment]
This is an upstream `webgpu.h` discussion and as it's already filed there, closing this.
