### ISSUE TITLE
Specifying / omitting compatibleSurface when calling requestAdapter()

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#153]
A short while ago I found that with a surface provided by wxWidgets, we would get 'Unable to request adapter: NotFound'. We were able to fix this by setting the `compatibleSurface` to null when calling `requestAdapter()`. All seemed fine.

With yesterday's update, however, if `compatibleSurface` is not specified, I get: 
```
panicked at 'Failed to configure surface: surface does not support the adapter's queue family', src/device.rs:680:9
```
This is in `wgpuDeviceCreateSwapChain` where it calls `GLOBAL.surface_configure(surface, device, &config)`. Unfortunately, specifying the surface still fails with our wxWidgets GUI backend.

@kvark any thoughts?

**Comment by kvark** [comment]
We didn't check for compatibility previously. Since wgpu has to be safe, this check was needed, and now it's in...
Let's find out why it's not compatible. Is this on Vulkan? How exactly do you get that surface?

**Comment by almarklein** [comment]
This problem with wx is on Linux (so Vulkan, yes). Haven't tried Windows or MacOS yet.

We [call](https://github.com/pygfx/wgpu-py/blob/268dadf149c97d36063f1c2e81ceddcb6abbe630/wgpu/gui/wx.py#L72-L73) wx's `.GetHandle()` and then [use](https://github.com/pygfx/wgpu-py/blob/268dadf149c97d36063f1c2e81ceddcb6abbe630/wgpu/backends/rs_helpers.py#L123-L135) `WGPUSurfaceDescriptorFromXlib`. I found it surprising that it fails for wx, since we use the same approach for glfw and qt, and there it works fine.

**Comment by kvark** [comment]
I suppose the next step would be trying to find any solid example on how Vulkan renders to wx, and see if we are doing anything different. This may be difficult, since most Vulkan examples in the wild are incorrect :/

**Comment by almarklein** [comment]
Some tests ...

Before the update:

* Using a made-up id, passing as `compatibleSurface`:  'Unable to request adapter: NotFound'
* Using a made-up id, passing null as `compatibleSurface`: 'Failed to configure surface: surface does not support the adapter's queue family'
* Using id from `.GetHandle`, passing as `compatibleSurface`:  'Unable to request adapter: NotFound'
* Using id from `.GetHandle`, passing null as `compatibleSurface`: works!

After the update:

* Using a made-up id, passing as `compatibleSurface`:  'Unable to request adapter: NotFound'
* Using a made-up id, passing null as `compatibleSurface`: 'Failed to configure surface: surface does not support the adapter's queue family'
* Using id from `.GetHandle`, passing as `compatibleSurface`:  'Unable to request adapter: NotFound'
* Using id from `.GetHandle`, passing null as `compatibleSurface`: 'Failed to configure surface: surface does not support the adapter's queue family'

Not sure what to make of this yet.

An example of wxwidgets with Vulkan, on Windows: https://github.com/jimorc/wxVulkanTutorial/tree/master/HelloTriangle

**Comment by almarklein** [comment]
I decided that this is likely more a problem for wgpu-py than wgpu-native. So I bumped a new tag and went to update wgpu-py, and now it *does* work. As in, I can still pass `null` for compatibleSurface, and get no errors. A pleasant surprise. I probably build the binary that I used for testing on a somewhat older commit or something.
