### ISSUE TITLE
Intermediate resource creation can fail silently

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#165]
For example, if you try to create a PipelineLayout with one BindGroupLayout, you may get an error like: `right: 1: BindGroupLayout[0] is no longer alive'`. Upon further investigation, this is because the creation of the BindGroupLayout returned `null`, which is unexpected; I've been caught by several issues now where an intermediate resource like this is `null` but no error on its creation was reported (and it's difficult to find out what went wrong because of it).

**Comment by radgeRayden** [comment]
For reference to what kind of problem can cause this, in this particular situation I tried to declare the type of a bind group layout entry as being Storage while visibility was set to Vertex (which requires ReadOnlyStorage).

**Comment by rajveermalviya** [comment]
Are you building from master? If you're, then you need to catch errors via [`wgpuDeviceSetUncapturedErrorCallback`](https://github.com/gfx-rs/wgpu-native/blob/b96f7e4ec687478b89b260da0b5799d776f8bb70/examples/triangle/main.c#L182).

**Comment by radgeRayden** [comment]
Thank you!
