### ISSUE TITLE
Memory statistics logging

### ISSUE THREAD

**Issue by sqaxomonophonen** [gfx-rs/wgpu-native#186]
Hi! I'm using wgpu-native semi-seriously (https://github.com/sqaxomonophonen/gpudl) and I've started worrying about whether or not my programs are leaking resources. So I'm running with a patched wgpu-native:

```diff
diff --git a/src/device.rs b/src/device.rs
index 2ab91fd..b773e51 100644
--- a/src/device.rs
+++ b/src/device.rs
@@ -782,6 +782,7 @@ pub extern "C" fn wgpuSwapChainPresent(swap_chain: id::SurfaceId) {
     let device_id = get_device_from_surface(surface_id);
     gfx_select!(device_id => GLOBAL.surface_present(surface_id))
         .expect("Unable to present swap chain");
+    log::debug!("Memory report: {:?}", GLOBAL.generate_report());
 }
 
 #[no_mangle]
```

E.g. if I forget to `wgpuTextureViewDrop()` the view returned by `wgpuSwapChainGetCurrentTextureView()` I can see the `num_occupied` for `texture_views` go up.

I don't know if it's something you're interested in having in wgpu-native? On one hand, a one-liner patch solves _my_ problem, but on the other hand it sounds like the perfect "bikeshed discussion" :-)
 - There are a dozen ways these kinds of statistics could be exposed, and I clearly chose the easiest, most unintrusive one, picking a function I know I'm going to call roughly once per frame (or more for 2+ windows), and logging from there.
 - Perhaps it ought to be part of `webgpu.h`, that is, after the team resolves this: https://github.com/webgpu-native/webgpu-headers/issues/9
 - Log output could be prettier, but then we're probably talking about a `Display` trait for `GlobalReport` in `wgpu`, which seems overkill?
 - I could use `log::trace!()` instead, but that output is already quite verbose
 - I don't recall ever worrying about leaking resources in OpenGL programs, so maybe I'm partly motivated by the "alpha-software state of everything WebGPU". But maybe OpenGL (~2) also tends to have slightly less resource management?

**Comment by kvark** [comment]
Let's do it, but perhaps in Debug-only?

**Comment by sqaxomonophonen** [comment]
Cool! There's a PR (#187)
