### ISSUE TITLE
Hide Rust-only entry points from cbindgen

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-native#20]
Things like `adapter_get_info` shouldn't be exposed to the C header.

**Comment by kvark** [comment]
C Header should only include "extern C" functions and repr(C) types. The end goal is #6, but in the meantime, we need to at least prevent `cbindgen` to skip non-C entries and types.

**Comment by paulkernfeld** [comment]
Is there any other work required to close this issue?
