### ISSUE TITLE
Unable to build examples on Windows

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#204]
While the library itself builds and works fine (using eg. `make package` with mingw), I haven't been able to build and run the examples. My OS is Windows 11.

Here's what I tried, on a fresh clone of the repository:
- under a mingw environment, call `make example-triangle`;
- under cmd on windows proper, follow the steps for the CI build [here](https://github.com/gfx-rs/wgpu-native/blob/91e14b8ffda0a5ec1d87fd27b7b9e8e62495720d/.github/workflows/ci.yml#L102), pointing LIBCLANG_PATH to llvm/bin (installed with `scoop`), using `make.exe` (also installed with scoop);
- tried same as above with a visual studio developer prompt

In all cases compilation stops with the following error:
```
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
WGPU_LIBRARY
    linked by target "compute" in directory C:/code/sources/wgpu-native/examples/compute
```

my target directory seems correctly populated:
```
ls target/debug/
build/  examples/     libwgpu_native.a*  libwgpu_native.dll.a*  wgpu_native.d*
deps/   incremental/  libwgpu_native.d*  libwgpu_native.rlib*   wgpu_native.dll*
```

**Comment by rajveermalviya** [comment]
Can you make sure which c/c++ compiler is used when running cmake?

**Comment by radgeRayden** [comment]
@rajveermalviya You're probably correct, as I see this:
`-- Building for: Visual Studio 16 2019`
and several other references to visual studio things. It would seem that it picked visual studio up simply for being installed on my system.
