### ISSUE TITLE
Inconsistent DLL naming in Windows release

### ISSUE THREAD

**Issue by eliemichel** [gfx-rs/wgpu-native#228]
Since [v0.10.4.1](https://github.com/gfx-rs/wgpu-native/releases/tag/v0.10.4.1), the dll provided the Windows build is called `libwgpu.dll`, whereas it was called `wgpu_native.dll` before.

However, the compagnon .lib file (which was missing in v0.10.4.1 but has been added back), still refers to `wgpu_native.dll` internally, as can be seen in the "DLL name" entry of all symbols listed by `dumpbin -headers libwgpu.lib`:

```
>dumpbin -headers libwgpu.lib
Microsoft (R) COFF/PE Dumper Version 14.29.30142.1
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file libwgpu.lib
[...]
  Version      : 0
  Machine      : 8664 (x64)
  TimeDateStamp: F24E255C
  SizeOfData   : 00000030
  DLL name     : wgpu_native.dll
  Symbol name  : wgpu_render_bundle_set_pipeline
  Type         : code
  Name type    : name
  Hint         : 99
  Name         : wgpu_render_bundle_set_pipeline
[...]
```

Possible workarounds:

 - Rename the dll back to wgpu_native.dll
 - Regenerate the .lib file with this kind of trick: https://stackoverflow.com/questions/9360280/how-to-make-a-lib-file-when-have-a-dll-file-and-a-header-file

**NB** Library names starting with "lib" is unix-style but not so windows-style, I think wgpu_native.dll was ok, wgpu.dll would be even better imho.

edit: I see that the symbol `wgpuAdapterEnumerateFeatures` is missing from the DLL

**Comment by almarklein** [comment]
I think #229 will do the trick.

> NB Library names starting with "lib" is unix-style but not so windows-style, I think wgpu_native.dll was ok, wgpu.dll would be even better imho.

Yeah, we are aware of that, but a consistent DLL name also has it's virtues, so we decided to use the same name on all platforms. Disclaimer: a uniform DLL name also makes our work at wgpu-py a bit easier :)

**Comment by almarklein** [comment]
Interestingly, the .lib seems not to be included anymore 🤔
