### ISSUE TITLE
Packaging fails due to incorrect lib name

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#231]
Had this issue locally and verified that it also happens in the latest github actions run: https://github.com/gfx-rs/wgpu-native/actions/runs/3557239659/jobs/5975115486#step:4:995

The problem seems to be that the Makefile is using a `LIB_NAME` variable that doesn't match the output from cargo: https://github.com/gfx-rs/wgpu-native/blob/master/Makefile#L46

**Comment by almarklein** [comment]
I think I might have broken it in #229 ... I can have a look after the holidays.
