### ISSUE TITLE
Why does this need to link against Winsock 2 on Windows? 

### ISSUE THREAD

**Issue by 1danielcoelho** [gfx-rs/wgpu-native#263]
Sorry if this is a stupid question, but I tried building and linking this for a native WebGPU program, and was surprised to see some unresolved external symbols to `__imp_WSAStartup`. 

That is defined within ws2_32.dll, which is the Winsock2 library... why does wgpu-native need access to web socket libraries? Granted, it has "web" in the name but I was expecting it to just talk to graphics APIs instead.

You can see all examples link against `d3dcompiler ws2_32 userenv bcrypt` on Windows, like [this one](https://github.com/gfx-rs/wgpu-native/blob/trunk/examples/triangle/CMakeLists.txt). Weirdly enough it doesn't seem to link against socket libraries on Mac/Linux. 

Thanks!

**Comment by rajveermalviya** [comment]
It comes from [rust std library](https://github.com/search?q=repo%3Arust-lang%2Frust%20WSAStartup&type=code
).
Sadly, we can't do anything about that :(

**Comment by rajveermalviya** [comment]
[here are all the libs required by rust std library](https://github.com/rust-lang/rust/blob/0004b3b984b19646c1f78b09ba497b7bd6e882c1/tests/run-make/tools.mk#L113-L118)
