### ISSUE TITLE
Panic when ending a render pass encoder after dropping a buffer that was previously bound to it

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#273]
During a frame I'm doing work that goes roughly like this:
- Bind a bind group with a storage buffer containing draw data
- Make a draw call to my main render pass
- Try to write to buffer, but it is too small. Recreate the buffer and a new bind group to go with it.
- Bind new group, issue another draw call.
- End pass.

When trying to end the pass, I get a [panic](https://gist.github.com/radgeRayden/222982bfdfe4cfaf487abaed1ffa1e03). After testing I concluded that keeping the unbound buffers / groups alive until after ending the pass ensures correct behaviour. However, it is my understanding that by dropping a resource, it is to be kept alive until anything that depends on it is also destroyed. I am not sure if this panic is intended behaviour for these resources specifically, or if this is a bug.

(Sorry I don't have code to show, but if necessary I can make a minimal C example.)

**Comment by radgeRayden** [comment]
Talked to @cwfitzgerald on matrix and this is intended behaviour currently. Should I keep the issue open to monitor the status of the fix to this with arcinization?

**Comment by rajveermalviya** [comment]
This will be fixed by #272.
