### ISSUE TITLE
No SType for WGPUInstanceEnumerateAdapterOptions

### ISSUE THREAD

**Issue by eliemichel** [gfx-rs/wgpu-native#275]
In `wgpu.h`, the type `WGPUInstanceEnumerateAdapterOptions` seems to be a potential target of some `nextInChain` pointer because it starts with a member of type `WGPUChainedStruct` that is called `chain`.

However, such an element of an extension chain must always be accompagnied with a SType to put in `chain.sType`. But `WGPUInstanceEnumerateAdapterOptions` has no such SType.

My guess is that `WGPUInstanceEnumerateAdapterOptions` was never supposed to be a target of some `nextInChain` (i.e., an extension), but rather a primary descriptor that may be extended. If so **its first member should be called `nextInChain` rather than `chain`.**

**Comment by rajveermalviya** [comment]
Thanks for reporting!
this happened in #224, a silly typo from my side, apologies!

Created #276 which includes a fix for it.
