### ISSUE TITLE
Modify WGPU.NET's description

### ISSUE THREAD

**Issue by Trivaxy** [gfx-rs/wgpu-native#287]
Just a tiny note - WGPU.NET as a library offers _both_ raw bindings to wgpu-native as well as optional wrappers, although the README labels as it as a wrapper library. 

I don't mean to nitpick, but can the description be tweaked? 😅

**Comment by rajveermalviya** [comment]
Sure, wanna send a PR?

**Comment by Trivaxy** [comment]
Sure. Thanks!
