### ISSUE TITLE
Update binary builds article

### ISSUE THREAD

**Issue by Korijn** [gfx-rs/wgpu-native#289]
This document: https://github.com/gfx-rs/wgpu-native/wiki/Binary-Releases#linux-builds

Is outdated, we don't use manylinux2010 anymore.

It's causing some minor confusions: https://github.com/pygfx/wgpu-py/issues/366

**Comment by rajveermalviya** [comment]
Thanks for reporting @Korijn, I have updated the wiki!

**Comment by Korijn** [comment]
Thanks for the quick response, and for adding the rationale for using the specific version. 👌
