### ISSUE TITLE
Sampler for a RGBA32_Float texture is not working

### ISSUE THREAD

**Issue by aparis69** [gfx-rs/wgpu-native#291]
When trying to create a sampler for a RGBA32_Float texture 2D array, the wgpu-native backend complains when binding the layout groups
> Device error: type 1 (message: Validation error caused by:
    In wgpuDeviceCreateBindGroup
      note: label = `Canvas Bind Group`
    Texture binding 0 expects sample type = Float { filterable: true }, but given a view with format = Rgba32Float
)

Even though I put the `FeatureName::Float32Filterable` in the require web GPU features in the initialization of the application.

The sampler is created as follows:
```cpp
SamplerDescriptor samplerDesc;
samplerDesc.addressModeU = AddressMode::ClampToEdge;
samplerDesc.addressModeV = AddressMode::ClampToEdge;
samplerDesc.addressModeW = AddressMode::ClampToEdge;
samplerDesc.magFilter = FilterMode::Nearest;
samplerDesc.minFilter = FilterMode::Nearest;
samplerDesc.mipmapFilter = MipmapFilterMode::Nearest;
samplerDesc.lodMinClamp = 0.0f;
samplerDesc.lodMaxClamp = 1.0f;
samplerDesc.compare = CompareFunction::Undefined;
samplerDesc.maxAnisotropy = 1;
data.sampler = m_device.createSampler(samplerDesc);
```
The texture is initialized as:
```cpp
data.tex2dArray = utils::createTexture2D(
	m_device,
	TextureFormat::RGBA32Float,
	w, h, d,
	TextureUsage::TextureBinding | TextureUsage::StorageBinding | TextureUsage::CopySrc | TextureUsage::CopyDst,
	texData.data()
);
```
The layout entry is set as:
```cpp
layoutEntries[0].binding = 0;
layoutEntries[0].texture.sampleType = TextureSampleType::Float;
layoutEntries[0].texture.viewDimension = TextureViewDimension::_2DArray;
```
When switching to the Dawn backend, I get no errors when running the app - so I'm guessing there is bug somewhere, or is tehre something that I'm doing wrong?

**Comment by rajveermalviya** [comment]
[float32-filterable](https://gpuweb.github.io/gpuweb/#float32-filterable) feature support is not yet implemented in `wgpu-core` (upstream), and thus unsupported in `wgpu-native`.

https://github.com/gfx-rs/wgpu/issues/2170

**Comment by aparis69** [comment]
Alright, thank you for this info, I'll close the issue then.
