### ISSUE TITLE
WGPUStorageTextureAccess missing access modes

### ISSUE THREAD

**Issue by simeks** [gfx-rs/wgpu-native#324]
Hi! 

I noticed WGPUStorageTextureAccess is missing `read-write` and `read-only`, which is part of the [specification](https://www.w3.org/TR/webgpu/#enumdef-gpustoragetextureaccess). Since these modes are available within the rust API already, is this something that just hasn't catched up or am I missing something?

Maybe this is better suited in https://github.com/webgpu-native/webgpu-headers?

**Comment by rajveermalviya** [comment]
Thanks for reporting this.
It was added to the [spec a ~month ago](https://github.com/gpuweb/gpuweb/pull/4326), the C header just hasn't caught up. Please file an issue/send a PR [there](https://github.com/webgpu-native/webgpu-headers/pulls).

**Comment by simeks** [comment]
Thank you for the quick reply, I've created a PR here now: https://github.com/webgpu-native/webgpu-headers/pull/250
