### ISSUE TITLE
Apparent memory leak

### ISSUE THREAD

**Issue by shadowndacorner** [gfx-rs/wgpu-native#350]
I've been integrating wgpu-native into a game engine I'm working on and have noticed what appears to be a memory leak.  At first I assumed I simply wasn't dereferencing a wgpu object, but after debugging for a while, I decided to check the [Learn WebGPU C++ example app](https://github.com/eliemichel/LearnWebGPU-Code/tree/step105) and noticed a leak at the exact same frequency (at least when limiting my engine's frame rate to the same as the app's - at a higher framerate, the leak is proportionally higher).

I'm not providing any of my own code here as I was able to reproduce the leak in the demo app linked above.  In my engine, I'm using the latest binary release of wgpu-native.  I believe the Learn WebGPU sample is using an older version due to the some API differences, but I'm not entirely sure which version.  On my machine (Windows 10), it seems to be leaking ~1MB every 5s, give or take.

The issue seems to apply to all backends equally.

**Comment by jimblandy** [comment]
Possibly related to gfx-rs/wgpu#2553?

**Comment by rajveermalviya** [comment]
Took a look at this today, and found bugs in that example and in the imgui's webgpu backend:
https://github.com/ocornut/imgui/pull/7245
https://github.com/eliemichel/LearnWebGPU-Code/pull/33

> Possibly related to https://github.com/gfx-rs/wgpu/issues/2553?

At least for the mentioned example that's unrelated, because with the above mentioned patches applied - there are no leaks.

**Comment by rajveermalviya** [comment]
@shadowndacorner Please reopen/reply if you think problem still exists, with a minimal repro.

**Comment by shadowndacorner** [comment]
@rajveermalviya You were absolutely right that those were causing the issue, and since my code was based on them, I was missing one of the releases.  Thanks!

**Comment by eliemichel** [comment]
Sorry about this, I updated all chapters of the guide!
