### ISSUE TITLE
Autogenerated binary modules for C++ does not support StorageTextureAccess ReadOnly and ReadWrite

### ISSUE THREAD

**Issue by SergeyLebedkin** [gfx-rs/wgpu-native#352]
In the original [webgpu.h](https://github.com/webgpu-native/webgpu-headers) we can see structure as folow:
```
 typedef enum WGPUStorageTextureAccess {
     WGPUStorageTextureAccess_Undefined = 0x00000000,
     WGPUStorageTextureAccess_WriteOnly = 0x00000001,
     WGPUStorageTextureAccess_ReadOnly = 0x00000002,
     WGPUStorageTextureAccess_ReadWrite = 0x00000003,
     WGPUStorageTextureAccess_Force32 = 0x7FFFFFFF
 } WGPUStorageTextureAccess WGPU_ENUM_ATTRIBUTE;
```
but in a headers, which are supplied with [binary C++ libraries ](https://github.com/gfx-rs/wgpu-native/releases) there are no ReadOnly and ReadWrite items:
```
typedef enum WGPUStorageTextureAccess {
    WGPUStorageTextureAccess_Undefined = 0x00000000,
    WGPUStorageTextureAccess_WriteOnly = 0x00000001,
    WGPUStorageTextureAccess_Force32 = 0x7FFFFFFF
} WGPUStorageTextureAccess WGPU_ENUM_ATTRIBUTE;
```
Even if try to add them manualy, library fails down:
`invalid storage texture access for storage texture binding layout`

**Comment by rajveermalviya** [comment]
The current release [`v0.18.1.4`](https://github.com/gfx-rs/wgpu-native/releases/tag/v0.18.1.4) only supports older version of `webgpu.h`. The `trunk` of `wgpu-native` already supports the newer `webgpu.h`, and a new release will happen this weekend.
