### ISSUE TITLE
Time for a first release?

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#36]
Now that the infrastructure is in place, we only have bump the version number and push a tag to make a release. Are there any pressing issues/PR's holding this off?

How shall we number releases from here? (We agreed that there is no need to align with the version of wgpu-core in any way.)

**Comment by kvark** [comment]
The changes will be coming, but you don't have to wait for them all.
I think releasing now is a good idea!

**Comment by cwfitzgerald** [comment]
We need to get #34 merged in first as right now it's impossible to make a sampler, but after that we should be golden.

**Comment by almarklein** [comment]
It looks like that PR is itself blocked by something else. Perhaps there a recent commit where the samples still worked that we can tag instead?

**Comment by kvark** [comment]
@almarklein yeah, that seems reasonable.
Do you maybe want to fix https://github.com/gfx-rs/wgpu-native/issues/38 before tagging?

**Comment by almarklein** [comment]
I could have a try, but unless I understand it incorrectly, the current tip is broken ("it's impossible to make a sampler"), and adding a fix for #38 will not fix that, right? I was suggesting to pick an earlier commit from when master was (more or less) stable.

**Comment by kvark** [comment]
ok, that's fair!

**Comment by almarklein** [comment]
Do you have a suggestion for a commit? :)  Is it known when the regression w.r.t. samplers was introduced?

**Comment by kvark** [comment]
9dfa7dc4e157ce2dfedee36636ff9b72ce1bd4b5 looks alright, at first sight

**Comment by almarklein** [comment]
Cool, I'll have a go tomorrow. Is better than nothing in any case ;)

**Comment by almarklein** [comment]
Done. Worked like a charm :)
