### ISSUE TITLE
Recent dependency on sockets API?

### ISSUE THREAD

**Issue by garettbass** [gfx-rs/wgpu-native#368]
I tried to upgrade to a more recent version of wgpu_native and discovered a compile time dependency on WSAStartup and other Windows socket APIs.  As someone using wgpu_native as a graphics API, I'm hesitant to link with sockets.  It would be nice if there were at least a clear public statement of why wgpu_native depends on socket API calls.  Thanks in advance for any clarification.

**Comment by rajveermalviya** [comment]
Dupe of #263 
Upstream bugs:
- https://github.com/rust-lang/rust/issues/119109
- https://github.com/rust-lang/rust/issues/80126

These links come from Rust standard library, no idea how we can avoid them currently. `wgpu-native` doesn't use any functions from `ws2_32`, and possibly even `userenv`  & `bcrypt`.

Anyway [here are the libraries](https://github.com/gfx-rs/wgpu-native/blob/9f863b6f872ca699d7e99b46eb6a716d2c171423/examples/triangle/CMakeLists.txt#L18) that you will need to link, currently.

**Comment by garettbass** [comment]
Thank you for linking to the list of required libraries.  I just kept adding libs until the compile errors went away and ended up with the same result.
