### ISSUE TITLE
triangle example crashes when creating a new swapchain

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#38]
As of the latest commit, the triangle example (and my program subsequently) crashes when creating a new swapchain, with the following backtrace: https://gist.github.com/radgeRayden/34173faca1f5b8d22ae086f9cd4dc89f

OS: Pop_OS 20.04
Graphics Adapter: Intel Corporation HD Graphics 5500 (rev 09)

**Comment by kvark** [comment]
It looks like we are missing the `x11` feature enabled for `gfx-backend-vulkan` here. See how wgpu-rs [does that](https://github.com/gfx-rs/wgpu-rs/blob/0e2b612c5f33862b328b179e09ae0598cdb21fae/Cargo.toml#L51).
