### ISSUE TITLE
For webassembly, Compile failed on versions EMSDK 3.1.56 and later

### ISSUE THREAD

**Issue by xrui94** [gfx-rs/wgpu-native#389]
I'm using emscripten tool chain to build wasm pogram, but my code has compiled failed on emsdk and later. Please check this [#issue16](https://github.com/eliemichel/WebGPU-Cpp/issues/16) for more details.

**Comment by eliemichel** [comment]
The issue is related to the `webgpu.hpp` wrapper, which is not provided by `wgpu-native` but rather an addition of my own in the [WebGPU-distribution](https://github.com/eliemichel/WebGPU-distribution). So I think we can close this issue and discuss this in the other one. ;)

**Comment by xrui94** [comment]
Ok, you are right.
