### ISSUE TITLE
Migrate to github actions

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-native#4]
Travis.org has been failing to send signals to us :(

**Comment by kvark** [comment]
See https://github.com/gfx-rs/wgpu-rs/pull/250 for inspiration

**Comment by Gordon-F** [comment]
@kvark I think i can help with this 😄

**Comment by kvark** [comment]
This one is the toughest. It will need the binary releases. If we at least move the regular CI bits to GH Actions, and then think about binary releases, it's already going to be a big win.

**Comment by almarklein** [comment]
FWIW we've had a good experience with Azure pipelines for CI, and [are building](https://github.com/Korijn/wgpu-bin) wgpu-native binaries on it.

**Comment by kvark** [comment]
@almarklein we are going to proceed with GH actions for now, for consistency. We'll be having Azure on the radar though, thank you for the link!

**Comment by Korijn** [comment]
> @almarklein we are going to proceed with GH actions for now, for consistency. We'll be having Azure on the radar though, thank you for the link! 

Feel free to copy and modify anything you need from our pipeline yaml when you get to binary releases. :)
