### ISSUE TITLE
WGPUCompareFunction value 0 is "Undefined"

### ISSUE THREAD

**Issue by DagAgren** [gfx-rs/wgpu-native#40]
When filling out a WGPUDepthStencilStateDescriptor, most of the time you are not using stencil functionality so you might want to not explicitly fill out the stencil_front and stencil_back WGPUStencilStateFaceDescriptor fields. However, they contain a WGPUCompareFunction field, and value 0 for this is "Undefined". wgpu will verify this value and panic if it is used, forcing you to always fill out at least the compare field in stencil_front and stencil_back, which seems like an issue with API ergonomics.

**Comment by kvark** [comment]
This will be resolved once we are able to land the updates in https://github.com/gfx-rs/wgpu-native/pull/34

**Comment by DagAgren** [comment]
Oh, I should specify, this is while building from the branch in #34.

**Comment by kvark** [comment]
Then #34 needs to be fixed :) cc @cwfitzgerald

**Comment by Sineaggi** [comment]
Is this still an issue? #34 was merged.

**Comment by kvark** [comment]
Let's close it then.
