### ISSUE TITLE
Obtaining AdapterInfo

### ISSUE THREAD

**Issue by DavidPeicho** [gfx-rs/wgpu-native#41]
Hi,

It's currently not possible to obtain an `AdapterInfo` C struct. The issue is that the struct from `wgpu-core` contains a Rusty string. As @cwfitzgerald proposed, we could ask the user to provide a pointer filled by the call to `get_info`. Otherwise, I guess we would need a call to `destroy_adapter_info` that could free an allocated `CString`? First idea sounds better.

Thanks!

**Comment by kvark** [comment]
Agreed, let's have the user providing the data.

**Comment by DavidPeicho** [comment]
Can work on this except if @cwfitzgerald wants to do it

**Comment by cwfitzgerald** [comment]
Be my guest! Always willing to help mentor on the matrix. https://matrix.to/#/#wgpu:matrix.org

**Comment by DavidPeicho** [comment]
Should we close this one now that #43 is merged?
