### ISSUE TITLE
Publish iOS and Android artifacts

### ISSUE THREAD

**Issue by ygdrasil-io** [gfx-rs/wgpu-native#415]
Hello, since we just added iOS and Android support to continuous delivery, could we have a new release with the latest wgpu version?

Until then, if anyone needs it, I have temporarily published this one: 
https://github.com/ygdrasil-io/wgpu-native/releases/tag/v0.0.0.4

**Comment by almarklein** [comment]
Done: https://github.com/gfx-rs/wgpu-native/releases/tag/v22.1.0.2

This release has 33 assets, 16 different platforms! 🚀
