### ISSUE TITLE
WGPUSType declaration is incompatible with C++

### ISSUE THREAD

**Issue by ryhor-spivak** [gfx-rs/wgpu-native#42]
https://github.com/gfx-rs/wgpu-native/blob/d9a12b8b05fb53dd7e36a5f4e6a462c6d9d873f1/ffi/wgpu.h#L199

In c++ mode enum already declare both 'enum WGPUSType' and 'WGPUSType' types and this typedef attempt to redefine it as different type which results in a compile error.

Why it's not declared as typedef enum just like all other enums in the header?

**Comment by cwfitzgerald** [comment]
So this is the C way of creating a enum with a particular backing size. We are incompatible with c++ currently in a couple ways right now. I need to sit down and give the cbindgen.toml a good look-over and update it and make us finally compatible with c++.

**Comment by dreammakeplay** [comment]
I guess one thing to do is rename the enum to "_WGPUSType" since the typedef is what matters here.

**Comment by kvark** [comment]
Wouldn't C++ project include the header in `extern "C"` anyway?

**Comment by dreammakeplay** [comment]
Not in this case. "extern C" only helps with name-mangling. It wont help with an enum that has the same name as a totally different typedef'd type. This is something that is totally valid to do in 'C' but not 'C++'.

**Comment by ryhor-spivak** [comment]
Looks like with a move to webgpu-headers/webgpu.h this was fixed.
