### ISSUE TITLE
Incompatible WGPUSType declaration in release webgpu.h

### ISSUE THREAD

**Issue by EricGrange** [gfx-rs/wgpu-native#428]
In the release include webgpu.h (at least v22.1.0.5 wgpu-windows-x86_64-gnu-release), the WGPUSType are defined like

```
typedef enum WGPUSType {
    WGPUSType_Invalid = 0x00000000,
    WGPUSType_SurfaceDescriptorFromMetalLayer = 0x00000001,
    WGPUSType_SurfaceDescriptorFromWindowsHWND = 0x00000002,
    WGPUSType_SurfaceDescriptorFromXlibWindow = 0x00000003,
```

which doesn't match the webgpu-native declaration (https://raw.githubusercontent.com/webgpu-native/webgpu-headers/refs/heads/main/webgpu.h) nor the Dawn declaration (which has the same declaraion as webgpu-native)

```
typedef enum WGPUSType {
    WGPUSType_Invalid = 0x00000000,
    WGPUSType_ShaderSourceSPIRV = 0x00000001,
    WGPUSType_ShaderSourceWGSL = 0x00000002,
    WGPUSType_RenderPassMaxDrawCount = 0x00000003,
    WGPUSType_SurfaceSourceMetalLayer = 0x00000004,
    WGPUSType_SurfaceSourceWindowsHWND = 0x00000005,
```

Additionally when trying to call wgpuInstanceCreateSurface with a WGPUSType_SurfaceDescriptorFromWindowsHWND in the surface descriptor chain, and using the standard webgpu.h declaration, this results in a fault.

**Comment by almarklein** [comment]
It generally takes a little while for `wgpu-native` to catch up to changes in `webgpu.h`(which is developed in a different repo). See e.g. a catchup in progress in #427. The released library should match the `webgpu.h` that's also in the release archive.

**Comment by EricGrange** [comment]
Thanks. I hadn't noticed that particular section of webgpu.h had been reorganized so recently.
