### ISSUE TITLE
add webgpu.yml on release

### ISSUE THREAD

**Issue by ygdrasil-io** [gfx-rs/wgpu-native#433]
Hello! I've started using the [webgpu.yml](https://github.com/webgpu-native/webgpu-headers/blob/main/webgpu.yml) to regenerate my Kotlin bindings, and it's definitely more convenient than working directly with the C headers. I was wondering if the community would be open to including this YAML file alongside the headers in each release ?

**Comment by almarklein** [comment]
Makes sense to me! [This line](https://github.com/gfx-rs/wgpu-native/blob/58c83560015701e28b8850ddd4515fcf0a4dd60d/Makefile#L59) moves the `webgpu.h` into the archive, so adding a line there for the yml file should do the trick.
