### ISSUE TITLE
Support for WSL

### ISSUE THREAD

**Issue by hermet** [gfx-rs/wgpu-native#448]
See https://github.com/gfx-rs/wgpu/issues/1443

----

Hello, I'm experiencing a crash on `wgpuSurfaceConfigure` (integrated with SDL+X11). This issue only occurs on a specific machine, while the same code runs successfully on others. Is there any way to diagnose the cause of the failure? Also, the program works on wgpu v19.x but only occurs with v22.x. Thanks.

```
thread '<unnamed>' panicked at src/lib.rs:582:5:
Error in wgpuSurfaceConfigure: Validation Error

Caused by:
  Invalid surface

stack backtrace:
   0:     0x7fb0fb960895 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd736fd5964392270
   1:     0x7fb0fb9847ab - core::fmt::write::hc6043626647b98ea
   2:     0x7fb0fb95e6cf - std::io::Write::write_fmt::h0d24b3e0473045db
   3:     0x7fb0fb96066e - std::sys_common::backtrace::print::h45eb8174d25a1e76
   4:     0x7fb0fb961a09 - std::panicking::default_hook::{{closure}}::haf3f0170eb4f3b53
   5:     0x7fb0fb9617aa - std::panicking::default_hook::hb5d3b27aa9f6dcda
   6:     0x7fb0fb961ea3 - std::panicking::rust_panic_with_hook::h6b49d59f86ee588c
   7:     0x7fb0fb961d84 - std::panicking::begin_panic_handler::{{closure}}::hd4c2f7ed79b82b70
   8:     0x7fb0fb960d59 - std::sys_common::backtrace::__rust_end_short_backtrace::h2946d6d32d7ea1ad
   9:     0x7fb0fb961ab7 - rust_begin_unwind
  10:     0x7fb0fb4b3283 - core::panicking::panic_fmt::ha02418e5cd774672
  11:     0x7fb0fb555f25 - wgpu_native::handle_error_fatal::ha412e282d23de10b
  12:     0x7fb0fb56f0ed - wgpuSurfaceConfigure
  ...
fatal runtime error: failed to initiate panic, error 5

```

**Comment by almarklein** [comment]
Have you set `compatibleSurface` in the `WGPURequestAdapterOptions`?

**Comment by hermet** [comment]
@almarklein of course.

**Comment by almarklein** [comment]
Do you have some more details about the machine and OS? And could you check the backend that is being used? IIRC I've seen this type of error when a system fell back to OpenGL.

**Comment by hermet** [comment]
@almarklein WSL with ubuntu 24.04 / nvidia geforce RTX 3060

**Comment by almarklein** [comment]
> WSL

Yeah, I've seen this with someone else on WSL. I think WSL does not support Vulkan properly, causing wgpu to fallback to an incompatible OpenGL. So in short: WSL is not yet supported. Also see https://github.com/gfx-rs/wgpu/issues/1443

**Comment by hermet** [comment]
@almarklein Got it, I assumed that reason but just wanna clarify it because, on WSL, it works with an older wgpu version but not with the latest version. and even another WSL machines work fine with the latest version even with the same WSL/ubunutu/wgpu/NVIDIA gpu card. I'm very confused. Anyway Thanks for clarifying this. It would be nicer if there is a useful logging method to debug the wgpu.  

Lastly, just so you know, we are building [ThorVG](https://github.com/thorvg/thorvg) vector graphics engine with WGPU.  :-) 

Thanks.

**Comment by almarklein** [comment]
>  it works with an older wgpu version but not with the latest version. and even another WSL machines work fine with the latest version even with the same WSL/ubunutu/wgpu/NVIDIA gpu card. I'm very confused

That *is* weird 🤔. 

> Lastly, just so you know, we are building [ThorVG](https://github.com/thorvg/thorvg) vector graphics engine with WGPU. :-)

Cool!
