### ISSUE TITLE
Triangle example does not draw triangle on macOS

### ISSUE THREAD

**Issue by mkeeter** [gfx-rs/wgpu-native#53]
I compiled and ran [`examples/triangle`](https://github.com/gfx-rs/wgpu-native/tree/master/examples/triangle) on macOS 10.13.6, using the 0.6.0 `libwgpu_native.dylib` (debug build).  There are no obvious errors, but the resulting image is completely green, and shows no triangle:
![Screen Shot 2020-10-14 at 5 48 46 PM](https://user-images.githubusercontent.com/745333/96049286-cd9bbc80-0e45-11eb-9d88-ced3e81e406b.png)

Adding `METAL_DEVICE_WRAPPER_TYPE=1` produces a single line of output:
```
2020-10-14 17:51:08.859 triangle[40323:46181835] Metal API Validation Enabled
```

**Comment by grovesNL** [comment]
It sounds like [an issue that we fixed upstream in gfx-backend-metal 0.6.2](https://github.com/gfx-rs/gfx/pull/3358/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR13) (usually caused by constant arrays in the shader on certain Intel cards), but we probably don't have that update in wgpu-native yet.

**Comment by mkeeter** [comment]
Good catch – if I switch to `WGPUPowerPreference_HighPerformance` (using the discrete vs integrated GPU), the triangle appears!

**Comment by kvark** [comment]
Ok, so this should go away on the next update/release, where the lockfile is updated with the latest backends.

**Comment by Sineaggi** [comment]
Triangle example works now on both discrete and integrated GPUs.

**Comment by grovesNL** [comment]
Ok great! I think we also need to update most/all versions in the lockfile because we still [reference gfx-backend-metal 0.6.0](https://github.com/gfx-rs/wgpu-native/blob/e3140b0d2ef2a22dd910f4487e15e22867fe93d1/Cargo.lock#L277)

**Comment by rajveermalviya** [comment]
As library migrated from `gfx-rs` to `wgpu-core` a while back. This is probably fixed, if it is still occurring please file a new issue.
