### ISSUE TITLE
Import *.lib for the Windows 32/64 packages is missing.

### ISSUE THREAD

**Issue by dreammakeplay** [gfx-rs/wgpu-native#57]
Hello, 

The import *.lib for Windows is missing from the Release packages ( @ https://github.com/gfx-rs/wgpu-native/releases)   Is the intention (for people that use the Release packages for Windows as opposed to compiling them themselves) to manually load the symbols for the DLL? Or is the import lib missing from the package?

Thanks in advance and for the great work, 
dmp

**Comment by kvark** [comment]
It would be good to include this in future releases!
