### ISSUE TITLE
Align the C header with Dawn

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-native#6]
https://github.com/webgpu-native/webgpu-headers

**Comment by paulkernfeld** [comment]
I wasn't able to find the `dawn.h` file linked at the top of the issue. I think it's now something within [this folder](https://source.chromium.org/chromium/chromium/src/+/master:out/Debug/gen/third_party/dawn/src/) but I'm not sure what.

**Comment by kvark** [comment]
@paulkernfeld I updated the subject with the actual path.

**Comment by cwfitzgerald** [comment]
We now gen from there, so this is good
