### ISSUE TITLE
Triangle example fails on current master

### ISSUE THREAD

**Issue by ajihyf** [gfx-rs/wgpu-native#63]
System: MacOS 11.0.1

It worked at b651cdc4e8bdd24836b50d90880d7ba2f6735bf6. Panics at e369639bf94e18b7d204eed1df032f9f657e10ad

> thread '<unnamed>' panicked at 'Validation(GlobalVariable { handle: Handle(2), name: "gl_VertexIndex", error: InvalidBuiltInType(VertexIndex) })', src/device.rs:669:5

**Comment by kvark** [comment]
Note: wgpu-rs master has moved the triangle example to WGSL. I suspect wgpu-native needs to do the same.
There is a known issue about the use of gl_VertexIndex/gl_InstanceIndex wrt validation in Naga.
