### ISSUE TITLE
No way to use wgsl in wgpu-native

### ISSUE THREAD

**Issue by Sineaggi** [gfx-rs/wgpu-native#69]
Currently wgpu-native hard-codes ShaderModuleSource::SpirV in https://github.com/gfx-rs/wgpu-native/blob/master/src/device.rs#L663. Should all supported shader sources be exposed by default?

**Comment by kvark** [comment]
We need to expose the standard webgpu-headers interface here: https://github.com/webgpu-native/webgpu-headers/blob/bc1c4afcce20a67913a16b3b6ee14f9777097fd3/webgpu.h#L682-L696
In this API, the shader module descriptor doesn't know about either SPIR-V or WGSL. Both of these come as the `pNext` structures.
