### ISSUE TITLE
masks could be FFI friendlier

### ISSUE THREAD

**Issue by radgeRayden** [gfx-rs/wgpu-native#73]
Due to the nature of C defines as direct text substitution, anything but straightforward literals can be problematic when using a header parser / importer. At the moment I'm having trouble ingesting the following #define'd masks:

```
WGPUFeatures
WGPUBufferUsage
WGPUTextureUsage
WGPUShaderStage
WGPUShaderFlags
WGPUColorWrite
```
The only obstacle here are the `uintNN_t` casts, which if my C understanding is correct could be substituted by UL/ULL literal suffixes.

**Comment by kvark** [comment]
Can you provide more detail on "I'm having trouble" part?
Also, are you suggesting to remove the casts in favor of suffixes? That sounds good to me!

**Comment by radgeRayden** [comment]
By trouble I mean that it isn't picked up automatically by the importer, and yeah substituting by suffixes would solve it.

**Comment by radgeRayden** [comment]
This doesn't seem to be a problem anymore after switching to the unified header.
