### ISSUE TITLE
CommandEncoder should be called CommandBufferEncoder.

### ISSUE THREAD

**Issue by procedural** [gfx-rs/wgpu-native#74]
Render Bundle Encoder encodes Render Bundles.

Command Buffer Encoder encodes Command Buffers.

**Comment by kvark** [comment]
That makes sense to me, and even though users of C/Rust side of the API will not appreciate a longer name here, it doesn't affect the Web, so we should do it for consistency.

**Comment by procedural** [comment]
Should I report this somewhere else as well? Any approximate dates when this API change may happen?

**Comment by kvark** [comment]
Yes, please file it on https://github.com/gpuweb/gpuweb/issues

**Comment by Kangz** [comment]
> even though users of C/Rust side of the API will not appreciate a longer name here

Yeah the longer name seems unnecessary. :/

**Comment by procedural** [comment]
> > even though users of C/Rust side of the API will not appreciate a longer name here
> 
> Yeah the longer name seems unnecessary. :/

@kvark marked this issue as a bug. Remove the label and close the issue if it's not a bug and the API won't be changed.

**Comment by kvark** [comment]
It's worth raising this in WebGPU anyway, first, for the record that we considered it.

**Comment by procedural** [comment]
> It's worth raising this in WebGPU anyway, first, for the record that we considered it.

@kvark @Kangz Are you two the only WebGPU API designers or there are other people that can vote for or against this change?

**Comment by kvark** [comment]
There are other people in the group as well. Thank you for filing!

**Comment by procedural** [comment]
> There are other people in the group as well.

It's not obvious where one should find the complete list of decision makers. Yesterday, [the blog post about first public working drafts](https://www.w3.org/blog/news/archives/9059) made the news, only you and Kai Ninomiya [are mentioned](https://www.w3.org/TR/2021/WD-webgpu-20210518/) as the current editors, so I'm not sure where else should I look.

**Comment by procedural** [comment]
Found the participants page, but not sure if a participant can vote or not: https://www.w3.org/community/gpu/participants

**Comment by Kangz** [comment]
There hasn't been any vote so far, it's all about consensus even if it sometimes took a lot of time to reach it.

**Comment by procedural** [comment]
@Kangz consensus between who exactly? I don't know, currently.

**Comment by Kangz** [comment]
Mostly browser vendors because other folks had less time to devote to the design of WebGPU. So Apple, Google, Microsoft and Mozilla.

**Comment by procedural** [comment]
@Kangz all the current employees of Apple, Google, Microsoft and Mozilla who work on browsers? Joe, an intern, can participate in voting for a WebGPU API change too?

**Comment by procedural** [comment]
"Can I see the judges, your honor?"

**Comment by procedural** [comment]
Yeah, this gets nowhere. Apparently it's yet another opaque decision making.

**Comment by kvark** [comment]
@procedural it's not always practical to follow a formal decision making process. We need to ship, we need to move fast. If we get dragged by each small bikeshed (like this rename), it's going to slow down the development. If there is no appetite in the working group for something, consider it rejected, even if you think it's needed.

**Comment by procedural** [comment]
@kvark can one learn who is the working group exactly?

**Comment by kvark** [comment]
@procedural formally, these people are in the community W3C group - https://www.w3.org/community/gpu/participants
But more importantly, by "WG" I generally mean the participants who:
  - devote enough energy and time to move this forwatd
  - have technical expertise
  - have a stake in the result (i.e. browser vendors)

Members from this subset of people have already seen your issue, and given no feedback it's safe to assume no appetite.

**Comment by procedural** [comment]
> it's not always practical to follow a formal decision making process. We need to ship, we need to move fast. If we get dragged by each small bikeshed (like this rename), it's going to slow down the development.

> it's safe to assume no appetite.

There will be appetite against it if you or someone else will just introduce the change without asking. So I take it as most people are against it.

**Comment by Kangz** [comment]
Oh good point, we should update that Jeff Gilbert replaced Dean Jackson.

**Comment by Kangz** [comment]
And done
