### ISSUE TITLE
Potential memory leak in DX12 backend on wgpu_queue_write_buffer

### ISSUE THREAD

**Issue by helikopterodaktyl** [gfx-rs/wgpu-native#76]
It seems that DX12 backend is leaking some memory in wgpu_queue_write_buffer. The bigger the buffer data being uploaded, the faster the memory usage goes up. I don't know how this function works underneath, but it seems whether it makes an internal copy  or the data to be sent or creates a buffer in local memory, that buffer doesn't get cleaned up afterwards.

I tried it with wgpu-native. I am not seeing this behavior with Vulkan backend.

**Comment by rajveermalviya** [comment]
Hi @helikopterodaktyl, I am closing this issue assuming it has been fixed.
If you think it is still present with the latest version, please feel free to comment back here with your findings.
