### ISSUE TITLE
Generating Rust types from C headers

### ISSUE THREAD

**Issue by kvark** [gfx-rs/wgpu-native#78]
Now that we are getting closer to #6 with PRs by @Sineaggi like #77, it seems to me that trying to re-define all the types that we need for C headers is a lot of redundant work. We already have those definitions in the shared C header, perhaps we could generate the Rust types automatically? https://github.com/rust-lang/rust-bindgen would help.

So wgpu-native would not need to define anything, it would just contain logic to map from the auto-generated types into `wgpu-core` and `wgpu-types`.

**Comment by cwfitzgerald** [comment]
This has happened.
