### ISSUE TITLE
Versioning of releases

### ISSUE THREAD

**Issue by almarklein** [gfx-rs/wgpu-native#80]
The readme says "Note: the version numbers of wgpu-native are not aligned with versions of wgpu or other crates!"

I can't fully remember whether we've discussed this earlier, but is it an idea to do let our releases follow wgpu-core, with an extra suffix number to represent the "snapshot". It won't be semver, but at least the version would mean *something*. Otherwise, perhaps calver is also an option? 

cc @Korijn

**Comment by Korijn** [comment]
Sure works for me. Just need to be careful that we stick to whatever you seems acceptable.

**Comment by almarklein** [comment]
@kvark Do you think it's reasonable to follow the version to  wgpu-core, e.g. `0.7.0.1`?

**Comment by kvark** [comment]
My concern with this is we are taking snapshots not from the published version, but from github. So, say, 0.7.0.45 could be much close to 0.8.0.0 than, say 0.8.0.1. So does this really give you what you want?
I don't mind either this scheme or calver. If you have a strong feeling, let's go with it.

**Comment by almarklein** [comment]
Yeah, it's not perfect, but at least the version means *something*. Running our own semver-like version for wgpu-native seems a bit silly since they're based on snapshots of wgpu-core either way. I'll think about it and do a release with the new scheme, whatever that will be :)

**Comment by Korijn** [comment]
How about we take the [debian scheme](https://www.debian.org/doc/debian-policy/ch-controlfields.html#version) as an example?

`[epoch:]upstream_version[-debian_revision]`

I like the [explanation on this page](https://readme.phys.ethz.ch/documentation/debian_version_numbers/):

## Simple generic examples
These examples show the necessary syntax

- Native package (Debian package = Upstream software): 123
  - Package version = Upstream version
- Non-native package: 123-3
  - 123 = Upstream software version
  - 3 = Debian revision, increments if only the packaging has changed between two package releases.
  - Means: Upstream version is 123 and it's the third Debian package based on that upstream version.
- Package with epoch, e.g. if upstream changed from date based to major.minor versioning
  - Old upstream version: 2013.06.06
  - New upstream version: 1.0
  - Problem: 1.0 < 2013.06.06
  - Solution: Add a (debian-specific) epoch:
  - Old package version (example): 2013.06.06-4 (upstream version + debian revision + implicit epoch of "0", i.e. 0:2013.06.06 is equivalent)
  - New package version: 1:1.0-1 (epoch of 1 + upstream version + debian revision)

**Comment by almarklein** [comment]
Oh wait, we're stuck to crate-specific versioning, because `wgpu_get_version()` https://github.com/gfx-rs/wgpu-native/blob/master/src/lib.rs#L158  We can change that function to include the pre-release tag (CARGO_PKG_VERSION_PRE) so we can have e.g. `0.7.1-1`.
