### ISSUE TITLE
bools in wgpu native structures

### ISSUE THREAD

**Issue by graphitemaster** [gfx-rs/wgpu-native#83]
I don't know if this is the right place to raise this issue, as it affects WebGPU as a specification.

Currently wgpu.h has some structures with `bool` in them. Under C, `sizeof(bool)` is the same size of int, so these have four byte size and alignment on most architectures, under C++ `bool` has size and alignment of char. This tends to be safe because C structure packing rules will have the compiler add three or seven bytes of padding proceeding the `bool` (depending on if a 4 or 8 byte int or pointer proceeds it), however this is not strictly true on all architectures. Vulkan avoids this issue by defining a 32-bit boolean type instead and using it in-situ of plain bools.

**Comment by graphitemaster** [comment]
This is problematic for back to back bools like in `WGPUBindGroupLayoutEntry` where I believe under C++ it simply does not work. As `multisampled` and `filtering` share the same 4 byte window. This also means Dawn and gpu-native are not ABI compatible.

**Comment by kvark** [comment]
WebGPU header is a C API strictly. If it has bools, and Dawn C++ wants to use them, that's a problem with Dawn C++ wrapper and not us. We'd just have `repr(C)` or use bindgen-generated structures from the header.

**Comment by graphitemaster** [comment]
Actually I'm wrong here, Rust has 1-byte size and alignment `bool`, yet cbindgen is emitting C `bool` for `repr(C)` which has 4-byte size and alignment. So this works in C++ (since it shares the same representation as Rust for `bool`) but actually fails under C. This appears like a bug in cbindgen.

**Comment by kvark** [comment]
ugh, unfortunate! Notably, we are shifting away from `cbindgen` towards doing the opposite - generating Rust types with `bindgen` from the shared header, and using them.

**Comment by graphitemaster** [comment]
I opened an issue for cbindgen here https://github.com/eqrion/cbindgen/issues/670

**Comment by graphitemaster** [comment]
So it appears Rust has actually defined their bool the same as `_Bool` in C. This means it's size and alignment is actually implementation-defined and not 1-byte size and alignment like most of the information you can find about this online is. In theory this means that Rust should align with C and C++ on bools. They may be implementation-defined but an implementation of C, C++, and Rust for a given platform should all agree with this for ABI sake.

**Comment by jimblandy** [comment]
I've never heard of a four-byte `bool`. Are you sure you're not just looking at different structure packing?

On Linux, at least, the following program prints `1`:

```
#include <stdio.h>

int main(int argc, char **argv) {
  printf("%zu\n", sizeof(_Bool));
}
```

Generally the machine-level representations of types are given by an ABI document, like [this one](https://gitlab.com/x86-psABIs/x86-64-ABI/-/blob/master/x86-64-ABI/low-level-sys-info.tex). Each C compiler or library needs to specify which ABI it uses.

(The ISO C2x standard itself has nothing to say about the size of `_Bool` other than §6.2.5 para 2: "An object declared as type _Bool is large enough to store the values 0 and 1.")
