### ISSUE TITLE
Windows DLLs missing functions.

### ISSUE THREAD

**Issue by ryhor-spivak** [gfx-rs/wgpu-native#96]
In v0.7.0.2 some functions are missing in dll/lib, for example wgpuQueueWriteTexture, wgpuBufferDestroy and wgpuTextureDestroy.

There are wgpu_buffer_destroy and wgpu_texture_destroy in dll exports, along with some others snake_case names from previous versions like wgpu_render_pass_draw, wgpu_render_pass_draw_indexed. But there is no header for them.

**Comment by almarklein** [comment]
This is due the fact that the code is now generated from the webgpu headers (instead of the other way around). Not sure what the implications for the missing destroy functions are, but I assume the resources are cleaned up automatically. I think `gpuQueueWriteTexture` is still there, is it not?

**Comment by ryhor-spivak** [comment]
Here is a full list of exported functions.
[exports.txt](https://github.com/gfx-rs/wgpu-native/files/6468349/exports.txt)

For queue there are only wgpuQueueSubmit and wgpuQueueWriteBuffer. wgpuQueueOnSubmittedWorkDone and wgpuQueueWriteTexture are missing.

**Comment by DevOrc** [comment]
It appears those functions haven't been ported since #85 

wgpuQueueSubmit and wgpuQueueWriteBuffer are defined here: 
https://github.com/gfx-rs/wgpu-native/blob/b4055903d75a2d95fcf71adc8f5ec13b48625e49/src/device.rs#L287-L309

**Comment by almarklein** [comment]
Several functions were added back in #95 and #96. These include all functions mentioned in the comments above except `wgpuQueueOnSubmittedWorkDone`.

**Comment by helikopterodaktyl** [comment]
Seems like wgpuAdapterGetProperties is also missing from the dll.

**Comment by rajveermalviya** [comment]
#246 somewhat fixed this, now all functions present in the headers should be exported by the lib.
But still some functions are unimplemented & they will cause a panic on call.
All of them are listed in `unimplemented.rs`:
https://github.com/gfx-rs/wgpu-native/blob/6f95ce3fc1cd8829f23401e98967112f00f940c2/src/unimplemented.rs#L1

So I think we should have a separate issues for implementing each of those functions, or group of similar functions.
Closing this in favor of that.
